name: gvn
object_base: orig/SGVEAF_D
object: sys/main.dol
hash: 54dfe8f178773b290746f7719c52a215d9390ae6
symbols: config/SGVEAF_D/symbols.txt
splits: config/SGVEAF_D/splits.txt
write_asm: true
mw_comment_version: 14

quick_analysis: false
detect_objects: true
detect_strings: true
